name : Building-blocks-trigers-1
on:
  push:
    paths:
    - 'README.md'
    branches :
      - main   

jobs :
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo " I' have been by triggered ${{github.event_name}}event."
      
  